"""Added nullable true on users table column updated_at

Revision ID: 4c428d0372a2
Revises: 759a54ca34d7
Create Date: 2025-09-24 19:55:43.950542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c428d0372a2'
down_revision: Union[str, Sequence[str], None] = '759a54ca34d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('resume', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('resume', 'name')
    # ### end Alembic commands ###
