"""Added constraints | Added provider column with enum(AuthProvider)

Revision ID: 56b9179544f7
Revises: 1140cc9c6335
Create Date: 2025-09-27 16:11:08.611402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql



# revision identifiers, used by Alembic.
revision: str = '56b9179544f7'
down_revision: Union[str, Sequence[str], None] = '1140cc9c6335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    authprovider = postgresql.ENUM('local', 'google', name='authprovider')
    authprovider.create(op.get_bind())

    op.add_column('user', sa.Column('provider', sa.Enum('local', 'google', name='authprovider'), nullable=False, server_default='local'))
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'provider')
    # ### end Alembic commands ###
