"""Added tenant collumn for resume model

Revision ID: 759a54ca34d7
Revises: 33481715ca29
Create Date: 2025-09-24 10:51:24.515814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '759a54ca34d7'
down_revision: Union[str, Sequence[str], None] = '33481715ca29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('tenant', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'resume', ['tenant'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resume', type_='unique')
    op.drop_column('resume', 'tenant')
    # ### end Alembic commands ###
